---
  - hosts: all

    tasks:
      - name: Set up firewall
        raw: systemctl disable firewalld
        raw: systemctl stop firewalld

      - name: Update Yum
        yum: name=* state=latest

      - name: Install httpd
        yum: name=httpd state=latest

      - name: Enable epel
        yum: name=epel-release state=installed

      - name: Add repository 'remi-repo'
        command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

      - name: install php70
        yum: name={{ item }} enablerepo=epel,remi,remi-php70 state=installed
        with_items:
          - php
          - php-mcrypt
          - php-mbstring
          - php-fpm
          - php-gd
          - php-xml
          - php-pdo
          - php-zip

      - name : link env file
        command: ln -s /opt/remi/php70/enable /etc/profile.d/php70.sh creates=/etc/profile.d/php70.sh

      - name: Install nano, git, etc
        yum: pkg={{ item }} state=installed
        with_items:
          - git
          - nano
          - curl
          - gcc
          - kernel-devel
          - wget
          - vim
          - man
          - unzip
          - nodejs
          - npm

      - name: Enable httpd
        service: name=httpd enabled=yes

      - name: Start apache
        service: name=httpd state=started
